Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -10,7 +10,8 @@ jobs:
       - run:
           name: Install Railway
           command: |
-            sudo npm install -g railway
+            sudo npm uninstall -g railway || true # Uninstall old Railway CLI if it exists (ignoring failure)
+            sudo npm install -g @railway/cli # Install new Railway CLI
             echo "RAILWAY_TOKEN=your-railway-token" >> $HOME/.railway
       - run:
           name: Build Dockerfile
@@ -30,7 +31,8 @@ jobs:
       - run:
           name: Install Railway
           command: |
-            sudo npm install -g railway
+            sudo npm uninstall -g railway || true # Uninstall old Railway CLI if it exists (ignoring failure)
+            sudo npm install -g @railway/cli # Install new Railway CLI
             echo "RAILWAY_TOKEN=your-railway-token" >> $HOME/.railway
       - run:
           name: Build Dockerfile
@@ -54,7 +56,8 @@ jobs:
       - run:
           name: Install Railway
           command: |
-            sudo npm install -g railway
+            sudo npm uninstall -g railway || true # Uninstall old Railway CLI if it exists (ignoring failure)
+            sudo npm install -g @railway/cli # Install new Railway CLI
             echo "RAILWAY_TOKEN=your-railway-token" >> $HOME/.railway
       - run:
           name: Build Dockerfile
